- Add OpenApi Swagger integration - Add springboot starter validation plugin to sort below error:
   jakarta.validation.NoProviderFoundException: Unable to create a Configuration,
   because no Jakarta Bean Validation provider could be found. Add a provider like Hibernate Validator (RI) to your classpath.

- Add OpenApi configuration
- Add security schemes to enable JWT authentication for all urls except the exempted ones